<template>
  <q-card v-if="security_role_cansave" inline class="q-ma-sm card-style featurecard col-grow">
    <q-card-section>
      <div class="text-h6">Export to Spreadsheet</div>
      <div class="text-subtitle2">Export figures into a google docs spreadsheet.</div>
    </q-card-section>
    <q-card-section>
      <q-btn color="primary" icon="save" label="Export to google sheets" @click="click_export" />
    </q-card-section>
  </q-card>
</template>

<script>
import { defineComponent } from 'vue'
import { Notify } from 'quasar'
import { useBackendConnectionStore } from 'stores/backend_connection'

export default defineComponent({
  name: 'SaveToGoogleSheetCompoennt',
  props: ['serialized_data', 'patch'],
  setup () {
    const backend_connection_store = useBackendConnectionStore()
    return {
      backend_connection_store
    }
  },
  data () {
    return {
    }
  },
  computed: {
    security_role_cansave () {
      return this.backend_connection_store.security_role_cansave
    },
  },
  methods: {
    click_export () {
      const tokenClient = google.accounts.oauth2.initTokenClient({
        client_id: this.$rjmgclientid,
        scope: this.$rjmgscopes,
        callback: this.execute_export,
      });
      if (gapi.client.getToken() === null) {
        // Prompt the user to select a Google Account and ask for consent to share their data
        // when establishing a new session.
        tokenClient.requestAccessToken({prompt: 'consent'});
      } else {
        // Skip display of account chooser and consent dialog for an existing session.
        tokenClient.requestAccessToken({prompt: ''});
      }
    },
    execute_export () {
      try {
        gapi.client.sheets.spreadsheets.create({
          properties: {
            title: 'evernetproperties.com-' + this.patch.name + '-' + this.serialized_data.dealbasicinfo.address,
          },
        }).then((response) => {
          // console.log('Spreadsheet ID: ' + response.result.spreadsheetId);
          this.make_updates_to_spreadsheet(response.result.spreadsheetId)
        });
      } catch (err) {
      this.sheet_api_error_handler(err)
        return;
      }
    },
    make_updates_to_spreadsheet (spreadsheetId) {
      const data = [];
      data.push({
        range: 'Sheet1!A1',
        values: [['=HYPERLINK("www.evernetproperties.com", "Project calculation generated by www.evernetproperties.com")']]
      });

      const body = {
        data: data,
        valueInputOption: 'USER_ENTERED',
      };
      try {
        gapi.client.sheets.spreadsheets.values.batchUpdate({
          spreadsheetId: spreadsheetId,
          resource: body,
        }).then((response) => {
          const result = response.result;
          console.log(`${result.totalUpdatedCells} cells updated.`);
          if (callback) callback(response);
        });
      } catch (err) {
        this.sheet_api_error_handler(err)
        return;
      }

      this.open_sheet(spreadsheetId)
    },
    open_sheet (spreadsheetId) {
      window.open('https://docs.google.com/spreadsheets/d/' + spreadsheetId, '_blank').focus()
    },
    sheet_api_error_handler (err) {
      console.log('Error-' + err.message)
      return;
    }
  }
})
</script>

<style>
</style>
